export const theme = {
  colors: {
    "primary-fixed": "#e1e0ff",
    "on-secondary-fixed": "#301400",
    "surface-dim": "#d2d9f4",
    "on-background": "#131b2e",
    "secondary-fixed": "#ffdcc5",
    "on-secondary": "#ffffff",
    "on-primary-fixed": "#07006c",
    "surface-container": "#eaedff",
    "on-secondary-container": "#683300",
    "secondary": "#944b00",
    "inverse-on-surface": "#eef0ff",
    "on-tertiary-fixed": "#301400",
    "surface-container-lowest": "#ffffff",
    "surface-container-low": "#f2f3ff",
    "primary": "#4648d4",
    "primary-fixed-dim": "#c0c1ff",
    "inverse-primary": "#c0c1ff",
    "surface-tint": "#494bd6",
    "tertiary-container": "#b55d00",
    "on-primary-container": "#fffbff",
    "secondary-container": "#fd943d",
    "primary-container": "#6063ee",
    "background": "#faf8ff",
    "on-primary-fixed-variant": "#2f2ebe",
    "on-tertiary": "#ffffff",
    "surface-variant": "#dae2fd",
    "error-container": "#ffdad6",
    "error": "#ba1a1a",
    "secondary-fixed-dim": "#ffb783",
    "on-secondary-fixed-variant": "#703700",
    "outline": "#767586",
    "on-surface-variant": "#464554",
    "tertiary-fixed-dim": "#ffb783",
    "on-tertiary-container": "#fffbff",
    "surface-container-high": "#e2e7ff",
    "on-tertiary-fixed-variant": "#703700",
    "surface-container-highest": "#dae2fd",
    "inverse-surface": "#283044",
    "surface-bright": "#faf8ff",
    "on-error": "#ffffff",
    "on-error-container": "#93000a",
    "outline-variant": "#c7c4d7",
    "on-primary": "#ffffff",
    "on-surface": "#131b2e",
    "tertiary-fixed": "#ffdcc5",
    "tertiary": "#904900",
    "surface": "#faf8ff"
  },
  borderRadius: {
    "DEFAULT": "0.25rem",
    "lg": "0.5rem",
    "xl": "0.75rem",
    "full": "9999px"
  },
  spacing: {
    "stack-lg": "32px",
    "container-max": "1280px",
    "margin-desktop": "48px",
    "stack-md": "16px",
    "gutter": "24px",
    "stack-sm": "8px",
    "margin-mobile": "16px"
  },
  fontFamily: {
    "body-md": ["var(--font-inter)", "sans-serif"],
    "body-lg": ["var(--font-inter)", "sans-serif"],
    "headline-md": ["var(--font-inter)", "sans-serif"],
    "body-sm": ["var(--font-inter)", "sans-serif"],
    "headline-lg-mobile": ["var(--font-inter)", "sans-serif"],
    "label-sm": ["var(--font-inter)", "sans-serif"],
    "headline-xl": ["var(--font-inter)", "sans-serif"],
    "label-md": ["var(--font-inter)", "sans-serif"],
    "headline-lg": ["var(--font-inter)", "sans-serif"]
  },
  fontSize: {
    "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
    "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
    "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
    "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
    "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
    "label-sm": ["12px", { "lineHeight": "16px", "fontWeight": "500" }],
    "headline-xl": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
    "label-md": ["14px", { "lineHeight": "16px", "letterSpacing": "0.01em", "fontWeight": "600" }],
    "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "700" }]
  }
};
